### ISSUE TITLE
Incorrect Use of $.inArray Breaks Rules with any and not-any conditions

### ISSUE THREAD

**Issue by clintonb** [miohtama/jquery-interdependencies#1]
jQuery.inArray() returns -1 or the index of the found element. The current code for condition evaluation does not properly handle the -1 and 0 cases.

_0 Case_
If an element is the first element of the array, inArray() will return 0 which is equivalent to false. Thus, we get false-negatives for "any" conditions and false-positives for "not-any" conditions.

_-1 Case_
-1, or any non-zero integer, is true. So, returning !-1 results in false, essentially reversing the expected result of the "not-any" condition.

**Comment by miohtama** [comment]
Fixed and emrged. Thanks for the patch!
